### ISSUE TITLE
Installation issues (multiple)

### ISSUE THREAD

**Issue by liubaoryol** [TUMcps/human-robot-gym#1]
https://eigen.tuxfamily.org/index.php?title=Main_Page is not opening.  Other way to get eigen3?

**Comment by liubaoryol** [comment]
Also, regarding this block:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/thummj/.mujoco/mujoco210/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so
```

I think it should work better if you replace `thummj` with `$USER`.

Also, more importantly, I don't have the `/usr/lib/x86_64-linux-gnu/libGLEW.so` file.. instead I have the following files when running `ls libGL*` in that directory:

```
libGLdispatch.so.0                 libGLESv2.so.2      libGLU.so.1.3.1              libGLX.so
libGLdispatch.so.0.0.0             libGLESv2.so.2.1.0  libGLX_indirect.so.0         libGLX.so.0
libGLESv1_CM_nvidia.so.1           libGL.so            libGLX_mesa.so.0             libGLX.so.0.0.0
libGLESv1_CM_nvidia.so.535.104.05  libGL.so.1          libGLX_mesa.so.0.0.0
libGLESv2_nvidia.so.2              libGL.so.1.7.0      libGLX_nvidia.so.0
libGLESv2_nvidia.so.535.104.05     libGLU.so.1         libGLX_nvidia.so.535.104.05
```

**Comment by liubaoryol** [comment]
Blocker: 

```
cd human-robot-gym/human_robot_gym/controllers/failsafe_controller/sara-shield
pip install -r requirements.txt
python setup.py install
```

The setup breaks because there is no `cmake` file.

**Comment by JakobThumm** [comment]
Hi, have you cloned with recursive submodules?
In the base human-robot-gym folder, try
```
git submodule init
git submodule update --recursive
```
Then cd into 
```
cd human-robot-gym/human_robot_gym/controllers/failsafe_controller/sara-shield
```
to check for the content. SaRA-shield is located here: https://github.com/JakobThumm/sara-shield

**Comment by JakobThumm** [comment]
Direct link to the Eigen 3.4 package: https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.bz2

**Comment by JakobThumm** [comment]
> Also, regarding this block:
> 
> ```
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/thummj/.mujoco/mujoco210/bin
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia
> export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so
> ```
> 
> I think it should work better if you replace `thummj` with `$USER`.
> 
> Also, more importantly, I don't have the `/usr/lib/x86_64-linux-gnu/libGLEW.so` file.. instead I have the following files when running `ls libGL*` in that directory:
> 
> ```
> libGLdispatch.so.0                 libGLESv2.so.2      libGLU.so.1.3.1              libGLX.so
> libGLdispatch.so.0.0.0             libGLESv2.so.2.1.0  libGLX_indirect.so.0         libGLX.so.0
> libGLESv1_CM_nvidia.so.1           libGL.so            libGLX_mesa.so.0             libGLX.so.0.0.0
> libGLESv1_CM_nvidia.so.535.104.05  libGL.so.1          libGLX_mesa.so.0.0.0
> libGLESv2_nvidia.so.2              libGL.so.1.7.0      libGLX_nvidia.so.0
> libGLESv2_nvidia.so.535.104.05     libGLU.so.1         libGLX_nvidia.so.535.104.05
> ```

Thank you for the user name spotting!
All these commands fix common known problems with [mujoco-py](https://github.com/openai/mujoco-py). If you can install and run mujoco-py without these fixes, you are good to go.
Concretely, the line
```
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so
```
helps against the issue
```
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libGLEW.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
according to [this github issue](https://github.com/openai/mujoco-py/issues/44).
So, you can also leave this line out. I will adapt the `README` accordingly.
If you are running into `libGLEW.so` issues, the mujoco-py github community might be able to help you out better than I do (but I can try).

**Comment by liubaoryol** [comment]
Fixed!

What fixed my installation issues was the link to the tar file and installing `sudo apt-get install libglew-dev libglfw3-dev` to make the `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so` work.

Thank you Jakob.

**Comment by JakobThumm** [comment]
I also updated the README with your suggestions. Thanks!
