### ISSUE TITLE
Cannot install python package pin

### ISSUE THREAD

**Issue by Ricky-Zhu** [TUMcps/human-robot-gym#2]
Hi,

I am installing the environment using the file `environment.yml`. But I just found that the package `pin` now cannot be installed due to the following issue:

ERROR: Could not find a version that satisfies the requirement cmeel-boost~=1.82.0 (from versions: 1.80.0, 1.81.0)

Could you please help to fix it?

Thank you!

**Comment by JakobThumm** [comment]
Hi, I just tested the install and cannot reproduce the error. 
You could install the pinocchio requirement on its own. If that doesn't work, please open an issue on the pinocchio repo and link that issue here.
Pinocchio is known for its unstable installation, and we want to eliminate that dependency in the future.

**Comment by meghbhalerao** [comment]
Is there any alternate package that you could suggest to pinocchio? Just out of curiosity, why the choice of Pinocchio as compared to other physics simulators such as MuJoCo, pybullet etc?

**Comment by JakobThumm** [comment]
Pinocchio is currently used for the self-collision detection and the static (environment) collision detection but not for human safety, which is done by sara-shield. We are planning to move the self-collision detection and the static collision detection to sara-shield in the future. Then, the installation will be simpler.

**Comment by JakobThumm** [comment]
You can use our software without the self-collision detection and the static collision detection, then you don't need Pinocchio, but you would need to remove the dependencies from a few files.
