### ISSUE TITLE
GLEW initalization error: Missing GL version.

### ISSUE THREAD

**Issue by UK-Roy** [TUMcps/human-robot-gym#5]
Hi,
Following the installation process provided by the human-robot-gym github link, everything works fine. 
But when I try to get the camera observations, I use the following arguments
```has_renderer=False```, ```use_camera_obs=True``` and ```has_offscreen_renderer=True```

But after running the file, it shows the error:

```
ERROR: GLEW initalization error: Missing GL version

Press Enter to exit ...
```
Currently I am using this package in conda environment and 
my openGL version: 
```OpenGL version string: 4.6.0 NVIDIA 535.171.04```

I tried every possible solution in the internet to solve this issue.

Regards,
Utsha

**Comment by JakobThumm** [comment]
Hi,
this is a common `mojuco-py` error. I'm redirecting you to the corresponding threads:
https://github.com/openai/mujoco-py/issues/408
https://github.com/openai/mujoco-py/issues/268
https://github.com/openai/mujoco-py/issues/44
https://github.com/openai/mujoco-py/issues/653
