### ISSUE TITLE
Not able to find human demo file from Vicon tracking 

### ISSUE THREAD

**Issue by meghbhalerao** [TUMcps/human-robot-gym#7]
The paper mentions that the the HR gym system uses human demos from the Vicon motion tracking system to train the RL agent. 

I was wondering where can I find those demo files? I looked at https://github.com/TUMcps/human-robot-gym/blob/mirror/human_robot_gym/training/config_icra_2024/environment_evaluation/dataset_creation/R.yaml#L39 and https://github.com/TUMcps/human-robot-gym/blob/mirror/human_robot_gym/training/config_icra_2024/environment_evaluation/dataset_creation/RHH.yaml#L40 etc. which seemed the most relevant thing to what I want but I am not able to find the `CMU/* files` anywhere? Are those the `vicon` tracking demo?

**Comment by JakobThumm** [comment]
Have you cloned the repo with submodules?
The human motion tracking files can be found in our [human-robot-animation repo](https://github.com/JakobThumm/human-robot-animations).

**Comment by meghbhalerao** [comment]
For future reference to others - the human animation clips are in the git submodule located here within the main repo - https://github.com/TUMcps/human-robot-gym/tree/mirror/human_robot_gym/models/assets/human/animations
